apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trivia-app
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trivia-app
            port:
              number: 80
    host: app.trivia.dnsb.io