apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: openai-chat-gui
spec:
  gateways:
    - trivia-gateway
  hosts:
    - openaichat.trivia.dnsb.io
  http:
    - route:
        - destination:
            host: openai-chat-gui
            port:
              number: 80
      match:
        - uri:
            prefix: /