apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: py-openai-api
spec:
  gateways:
    - trivia-gateway
  hosts:
    - py-openai-api.trivia.dnsb.io
  http:
    - route:
        - destination:
            host: py-openai-api
            port:
              number: 5555
      match:
        - uri:
            prefix: /chatbot